apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hostport-operator
  namespace: operators
  labels:
    app.kubernetes.io/name: hostport-operator
    app.kubernetes.io/component: metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hostport-operator
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http

